/*
 * board.h — Harmonic Reaper wand pin assignments (nRF52840)
 *
 * Author: jayis1
 * License: GPL-2.0
 *
 * Pin map for the production wand PCB. All assignments are stable across
 * revisions and match the KiCad schematic in ../kicad/device.kicad_sch.
 *
 * nRF52840 QFAA has P0.00..P0.31 and P1.00..P1.15 (48 GPIO total).
 * "P1.xx" pins are encoded as 32+xx throughout this codebase.
 */
#ifndef HARMONIC_REAPER_BOARD_H
#define HARMONIC_REAPER_BOARD_H

#include <stdint.h>

/* ====================================================================== */
/*  LED indicators (active high)                                           */
/* ====================================================================== */
#define LED_RED_PIN        13   /* P0.13  — status / error                */
#define LED_GREEN_PIN      14   /* P0.14  — armed / sweeping              */
#define LED_BLUE_PIN       15   /* P0.15  — hit indicator                 */

/* ====================================================================== */
/*  OLED SSD1306 — SPI2 (128×64)                                           */
/*  Wired 4-wire SPI. D/C# driven by a GPIO.                              */
/* ====================================================================== */
#define OLED_SCK_PIN       27   /* P0.27  → SPIM2.SCK                    */
#define OLED_MOSI_PIN      26   /* P0.26  → SPIM2.MOSI                   */
#define OLED_DC_PIN        25   /* P0.25  → OLED D/C#                    */
#define OLED_CS_PIN        24   /* P0.24  → OLED CS# (active low)        */
#define OLED_RST_PIN       23   /* P0.23  → OLED RES# (active low)       */
#define OLED_SPI_BASE      NRF_SPIM2_BASE

/* ====================================================================== */
/*  TX synthesizer ADF4159 — SPI0                                         */
/* ====================================================================== */
#define ADF4159_SCK_PIN    4    /* P0.04  → SPIM0.SCK                    */
#define ADF4159_MOSI_PIN   5    /* P0.05  → SPIM0.MOSI                   */
#define ADF4159_MISO_PIN   6    /* P0.06  → SPIM0.MISO                   */
#define ADF4159_LE_PIN     7    /* P0.07  → ADF4159 latch-enable (CS#)    */
#define ADF4159_CE_PIN     8    /* P0.08  → ADF4159 chip enable          */
#define ADF4159_SPI_BASE   NRF_SPIM0_BASE

/* ====================================================================== */
/*  PA / AGC QPL9547 — same SPI0 bus, separate CS                          */
/*  Plus a 6-bit parallel AGC DAC (R-2R ladder on P0.30..P0.31+P1.00..P1.03)
/*  for fast coarse gain in pulse mode.                                  */
/* ====================================================================== */
#define QPL9547_CS_PIN     9    /* P0.09  → QPL9547 CS#                  */
#define QPL9547_TX_EN_PIN  10   /* P0.10  → PA enable (active high)       */
#define AGC_DAC_D0_PIN     30   /* P0.30  bit0 (LSB)                     */
#define AGC_DAC_D1_PIN     31   /* P0.31  bit1                            */
#define AGC_DAC_D2_PIN     32   /* P1.00  bit2                            */
#define AGC_DAC_D3_PIN     33   /* P1.01  bit3                            */
#define AGC_DAC_D4_PIN     34   /* P1.02  bit4                            */
#define AGC_DAC_D5_PIN     35   /* P1.03  bit5 (MSB) — 64 levels           */

/* ====================================================================== */
/*  2f₀ receiver AD9361 — SPI1                                             */
/* ====================================================================== */
#define AD9361_SCK_PIN     11   /* P0.11  → SPIM1.SCK                    */
#define AD9361_MOSI_PIN    12   /* P0.12  → SPIM1.MOSI                   */
#define AD9361_MISO_PIN    16   /* P0.16  → SPIM1.MISO                   */
#define AD9361_CS_PIN      17   /* P0.17  → AD9361 CS#                   */
#define AD9361_RESET_PIN   18   /* P0.18  → AD9361 RESET#                */
#define AD9361_SPI_BASE    NRF_SPIM1_BASE

/* I/Q data is clocked out on parallel CMOS bus → captured by FPGA.
 * The MCU never touches the I/Q pins directly; FPGA owns them. */

/* ====================================================================== */
/*  3f₀ IF channel: ADL5802 mixer + AD9226 ADC (200 MHz IF)               */
/*  The ADC sample clock is generated by the FPGA. MCU only controls the  */
/*  mixer bias and ADC power-down via I²C expander.                       */
/* ====================================================================== */
#define AD9226_PD_PIN      20   /* P0.20  → ADC power-down (active high)  */
#define ADL5802_EN_PIN     21   /* P0.21  → mixer enable                  */

/* ====================================================================== */
/*  Spartan-7 FPGA control — SPI1 (shared bus with AD9361)                */
/*  plus dedicated GPIOs for PROGRAM_B, DONE, IRQ                          */
/* ====================================================================== */
#define FPGA_CS_PIN        22   /* P0.22  → FPGA SPI CS#                  */
#define FPGA_PROG_B_PIN    19   /* P0.19  → FPGA PROGRAM_B (active low)   */
#define FPGA_DONE_PIN      29   /* P0.29  ← FPGA DONE (input, pull-up)    */
#define FPGA_IRQ_PIN       28   /* P0.28  ← FPGA classifier-ready IRQ      */

/* ====================================================================== */
/*  IMU ICM-42688 — SPI3                                                  */
/* ====================================================================== */
#define IMU_SCK_PIN        41   /* P1.09  → SPIM3.SCK                    */
#define IMU_MOSI_PIN       40   /* P1.08  → SPIM3.MOSI                   */
#define IMU_MISO_PIN       42   /* P1.10  → SPIM3.MISO                   */
#define IMU_CS_PIN         43   /* P1.11  → IMU CS#                      */
#define IMU_INT1_PIN       44   /* P1.12  ← IMU data-ready IRQ            */
#define IMU_SPI_BASE       NRF_SPIM3_BASE

/* ====================================================================== */
/*  Haptic DRV2605 — I²C (TWIM0)                                           */
/* ====================================================================== */
#define HAPTIC_SDA_PIN     2    /* P0.02  → TWIM0.SDA                    */
#define HAPTIC_SCL_PIN     3    /* P0.03  → TWIM0.SCL                    */
#define HAPTIC_I2C_BASE    0x40003000u   /* TWIM0 base */
#define HAPTIC_I2C_ADDR    0x5A

/* ====================================================================== */
/*  microSD on SPIM2 (shared with OLED — polled, never simultaneously)    */
/* ====================================================================== */
#define SD_SCK_PIN         OLED_SCK_PIN
#define SD_MOSI_PIN        OLED_MOSI_PIN
#define SD_MISO_PIN        45   /* P1.13  ← SD MISO (OLED has no MISO)    */
#define SD_CS_PIN          46   /* P1.14  → SD CS#                       */
#define SD_DETECT_PIN      47   /* P1.15  ← SD card-detect (active low)  */
#define SD_SPI_BASE        OLED_SPI_BASE

/* ====================================================================== */
/*  USB-C (for CDC + charging backchannel) — fixed nRF52 USB peripheral    */
/* ====================================================================== */
/* nRF52840 USB is on dedicated pins (D+, D-) — no GPIO mux.               */

/* ====================================================================== */
/*  Power / battery                                                       */
/* ====================================================================== */
#define BATT_SENSE_SAADC_CH 0  /* SAADC CH0 = VDD/4 (internal)            */
#define CHARGE_STAT_PIN     39 /* P1.07  ← charger status (active low)    */

/* ====================================================================== */
/*  Reset / boot0 — nRF52840 has fixed RESET; no boot0 pin.                */
/* ====================================================================== */

/* ====================================================================== */
/*  Aggregate mode enum for the top-level state machine                    */
/* ====================================================================== */
typedef enum {
    MODE_IDLE = 0,        /* TX off, OLED home, BLE advertising           */
    MODE_QUIET_RX,        /* RX only — baseline noise scan, TX gated off  */
    MODE_SWEEP_CW,        /* CW TX at set power, normal detection         */
    MODE_SWEEP_PULSED,    /* Pulsed TX, randomized PRF (default mode)     */
    MODE_CALIBRATE,       /* Reference diode / baseline wizard            */
    MODE_FAULT,           /* Error state, OLED shows fault, BLE reports    */
} sweep_mode_t;

/* ====================================================================== */
/*  Default operating parameters (overridable from app over BLE)           */
/* ====================================================================== */
#define DEFAULT_TX_POWER_DBM       0       /* 0 dBm nominal; AGC trims   */
#define DEFAULT_PULSE_PRF_HZ       4000    /* 4 kHz pulse repetition      */
#define DEFAULT_PULSE_WIDTH_NS     200     /* 200 ns pulses               */
#define DEFAULT_RATIO_THRESH_SEMI  6       /* +6 dB → semiconductor        */
#define DEFAULT_RATIO_THRESH_METAL (-6)    /* −6 dB → dissimilar metal     */
#define DEFAULT_HIT_STICKINESS     3       /* consecutive samples to fire  */
#define DEFAULT_AGC_TARGET_DBFS    (-12)   /* keep 2f0 at −12 dBFS        */

#endif /* HARMONIC_REAPER_BOARD_H */
/* EOF — board.h — jayis1 */