/* PDM Trust Probe FPGA register map
 * Author: jayis1
 * SPDX-License-Identifier: MIT
 */
#ifndef PTP_REGISTERS_H
#define PTP_REGISTERS_H
#include <stdint.h>
#define PTP_FPGA_ID_EXPECTED 0x50444D54u
#define PTP_USB_MAGIC 0x31505450u
#define PTP_PROTOCOL_VERSION 1u
enum ptp_fpga_reg {
 REG_ID=0x00u, REG_CONTROL=0x04u, REG_STATUS=0x08u, REG_CLOCK_HZ=0x0Cu,
 REG_EDGE_ERRORS=0x10u, REG_FIFO_LEVEL=0x14u, REG_FIFO_DATA=0x18u,
 REG_CHANNEL_MASK=0x1Cu, REG_GATE_LIMIT=0x20u, REG_INJECT_PATTERN=0x24u,
 REG_INJECT_WORDS=0x28u, REG_WATCHDOG=0x2Cu
};
#define CTRL_CAPTURE_ENABLE (1u<<0)
#define CTRL_ACTIVE_PATH (1u<<1)
#define CTRL_INJECT_ENABLE (1u<<2)
#define CTRL_FIFO_RESET (1u<<3)
#define STATUS_PLL_LOCKED (1u<<0)
#define STATUS_FIFO_OVERFLOW (1u<<1)
#define STATUS_CLOCK_RANGE (1u<<2)
#define STATUS_CONTENTION (1u<<3)
#define STATUS_BYPASS_CLOSED (1u<<4)
typedef enum { CMD_INFO=1, CMD_STATUS=2, CMD_CAPTURE_START=3, CMD_CAPTURE_STOP=4,
 CMD_POLICY_SET=5, CMD_ARM=6, CMD_PATTERN_RUN=7, CMD_EVENT_READ=8, CMD_RESET=9 } ptp_command_t;
typedef enum { ST_OK=0, ST_BAD_FRAME=1, ST_DENIED=2, ST_RANGE=3, ST_BUSY=4, ST_HW_FAULT=5 } ptp_status_t;
#endif
