/**
 * drivers/usb_ft601.c — FT601 USB 3.0 FIFO Bridge Driver Implementation
 *
 * Complete driver for the FTDI/Bridgetek FT601Q-B-T USB 3.0 to
 * 32-bit synchronous FIFO bridge. Provides high-speed data egress
 * from the FPGA to the companion analysis PC.
 *
 * The FT601Q operates in 32-bit synchronous FIFO mode at 100 MHz,
 * providing up to 400 MB/s raw bandwidth (limited by USB 3.0
 * effective throughput of ~350-400 MB/s).
 *
 * FIFO Protocol:
 *   TX (FPGA → USB): Wait for TXE# low, place data on D[31:0],
 *                     assert WR# low, de-assert WR#.
 *   RX (USB → FPGA): Wait for RXF# low, assert OE# low,
 *                     assert RD# low, read D[31:0], de-assert RD#.
 *
 * Author: jayis1
 * Date: 2026-06-16
 */

#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include "../board.h"
#include "../registers.h"
#include "usb_ft601.h"
#include "crc32c.h"

/*============================================================================
 * INTERNAL CONSTANTS
 *============================================================================*/

#define FT601_RESET_HOLD_US      1000UL    /* 1 ms reset hold */
#define FT601_INIT_WAIT_US       10000UL   /* 10 ms after reset */
#define FT601_ENUM_TIMEOUT_US    5000000UL /* 5 s enumeration timeout */
#define FT601_TX_WORD_TIMEOUT_US 1000UL    /* 1 ms per word timeout */
#define FT601_RX_WORD_TIMEOUT_US 1000UL    /* 1 ms per word timeout */
#define FT601_MAX_PAYLOAD        4096      /* Max payload per frame */

/*============================================================================
 * GLOBAL STATE
 *============================================================================*/

static uint32_t g_tx_byte_count = 0;
static uint32_t g_rx_byte_count = 0;
static int g_enumerated = 0;

/*============================================================================
 * INITIALIZATION
 *============================================================================*/

int ft601_init(void) {
    /* 1. Assert FT601 reset */
    ASSERT_LOW(FT_RESET_PIN);
    delay_us(FT601_RESET_HOLD_US);

    /* 2. Start 100 MHz clock to FT601 */
    /* The clock is generated by FPGA PLL1 and routed to FT_CLK_PIN.
     * It should already be running from PLL initialization. */

    /* 3. Release FT601 reset */
    DEASSERT_LOW(FT_RESET_PIN);
    delay_us(FT601_INIT_WAIT_US);

    /* 4. Set initial control signal states */
    DEASSERT_LOW(FT_SIWU_PIN);   /* SIWU# inactive */
    DEASSERT_LOW(FT_WR_PIN);     /* WR# inactive */
    DEASSERT_LOW(FT_RD_PIN);     /* RD# inactive */
    DEASSERT_LOW(FT_OE_PIN);     /* OE# inactive (FPGA not driving bus) */

    /* 5. Wait for USB enumeration
     * FT601 drives SUSPEND# low when enumerated and active */
    int timeout = FT601_ENUM_TIMEOUT_US;
    while (IS_ASSERTED(FT_SUSPEND_PIN)) {
        if (--timeout <= 0) {
            return -1;  /* Enumeration timeout */
        }
        delay_us(1);
    }

    g_enumerated = 1;

    /* 6. Reset byte counters */
    g_tx_byte_count = 0;
    g_rx_byte_count = 0;

    return 0;
}

/*============================================================================
 * RESET
 *============================================================================*/

void ft601_reset(void) {
    g_enumerated = 0;

    ASSERT_LOW(FT_RESET_PIN);
    delay_us(FT601_RESET_HOLD_US);
    DEASSERT_LOW(FT_RESET_PIN);
    delay_us(FT601_INIT_WAIT_US);

    /* Re-initialize control signals */
    DEASSERT_LOW(FT_SIWU_PIN);
    DEASSERT_LOW(FT_WR_PIN);
    DEASSERT_LOW(FT_RD_PIN);
    DEASSERT_LOW(FT_OE_PIN);

    /* Wait for re-enumeration */
    int timeout = FT601_ENUM_TIMEOUT_US;
    while (IS_ASSERTED(FT_SUSPEND_PIN)) {
        if (--timeout <= 0) {
            return;  /* Failed to re-enumerate */
        }
        delay_us(1);
    }

    g_enumerated = 1;
}

/*============================================================================
 * STATUS
 *============================================================================*/

int ft601_is_enumerated(void) {
    return g_enumerated && IS_DEASSERTED(FT_SUSPEND_PIN);
}

/*============================================================================
 * RAW PACKET TRANSMIT
 *============================================================================*/

int ft601_tx_packet(const uint8_t *data, uint16_t len_bytes) {
    int timeout;

    if (!data || len_bytes == 0) {
        return -1;
    }

    /* Data length must be multiple of 4 for 32-bit FIFO */
    if (len_bytes & 0x3) {
        return -2;  /* Not aligned to 32-bit */
    }

    uint16_t words = len_bytes / 4;

    /* Wait for TXE# low (FIFO has space) */
    timeout = FT601_TX_WORD_TIMEOUT_US;
    while (IS_ASSERTED(FT_TXE_PIN)) {
        if (--timeout <= 0) {
            return -3;  /* TXE timeout */
        }
        delay_us(1);
    }

    /* Assert OE# low to enable FPGA outputs on the data bus */
    ASSERT_LOW(FT_OE_PIN);

    /* Write each 32-bit word */
    for (uint16_t i = 0; i < words; i++) {
        /* Wait for TXE# low before each word */
        timeout = FT601_TX_WORD_TIMEOUT_US;
        while (IS_ASSERTED(FT_TXE_PIN)) {
            if (--timeout <= 0) {
                DEASSERT_LOW(FT_OE_PIN);
                return -3;  /* TXE timeout mid-packet */
            }
            delay_us(1);
        }

        /* Place data on bus */
        uint32_t word;
        memcpy(&word, data + i * 4, 4);
        REG_WRITE(USB_TX_FIFO_DATA_REG, word);

        /* Assert WR# low (write strobe) */
        ASSERT_LOW(FT_WR_PIN);
        delay_us(1);  /* Minimum WR# pulse width: 10 ns, 1 µs is safe */
        DEASSERT_LOW(FT_WR_PIN);
    }

    /* De-assert OE# */
    DEASSERT_LOW(FT_OE_PIN);

    /* Update byte count */
    g_tx_byte_count += len_bytes;
    REG_WRITE(USB_TX_BYTE_COUNT_REG, g_tx_byte_count);

    return 0;
}

/*============================================================================
 * RAW PACKET RECEIVE
 *============================================================================*/

int ft601_rx_packet(uint8_t *buf, uint16_t max_len) {
    int timeout;
    uint16_t words_received = 0;

    if (!buf || max_len < 4) {
        return -1;
    }

    /* Check if data available (RXF# low = FIFO has data) */
    if (IS_DEASSERTED(FT_RXF_PIN)) {
        return 0;  /* No data available */
    }

    /* Assert OE# low (FT601 drives bus, FPGA reads) */
    ASSERT_LOW(FT_OE_PIN);

    /* Read words while data is available */
    while (IS_ASSERTED(FT_RXF_PIN) && (words_received * 4) < max_len) {
        /* Assert RD# low (read strobe) */
        ASSERT_LOW(FT_RD_PIN);
        delay_us(1);  /* Wait for data to appear on bus */
        DEASSERT_LOW(FT_RD_PIN);

        /* Read data from bus */
        uint32_t word = REG_READ(USB_RX_FIFO_DATA_REG);
        memcpy(buf + words_received * 4, &word, 4);
        words_received++;

        /* Check if more data is available */
        timeout = FT601_RX_WORD_TIMEOUT_US;
        while (IS_DEASSERTED(FT_RXF_PIN) && timeout > 0) {
            delay_us(1);
            timeout--;
        }
    }

    /* De-assert OE# */
    DEASSERT_LOW(FT_OE_PIN);

    uint16_t bytes_received = words_received * 4;
    g_rx_byte_count += bytes_received;
    REG_WRITE(USB_RX_BYTE_COUNT_REG, g_rx_byte_count);

    return bytes_received;
}

/*============================================================================
 * FRAMED RESPONSE TRANSMIT
 *============================================================================*/

int ft601_tx_response(uint8_t cmd, const uint8_t *payload,
                      uint16_t payload_len) {
    uint8_t frame[FT601_MAX_PAYLOAD + 13];  /* 13 header + max payload */
    uint16_t frame_len;
    uint32_t crc;

    if (payload_len > FT601_MAX_PAYLOAD) {
        return -1;  /* Payload too large */
    }

    /* Build frame header */
    frame[0] = SYNC_MARKER_0;
    frame[1] = SYNC_MARKER_1;
    frame[2] = SYNC_MARKER_2;
    frame[3] = SYNC_MARKER_3;
    frame[4] = SYNC_MARKER_4;
    frame[5] = SYNC_MARKER_5;
    frame[6] = cmd;
    frame[7] = (payload_len >> 8) & 0xFF;
    frame[8] = payload_len & 0xFF;

    /* Copy payload */
    if (payload && payload_len > 0) {
        memcpy(frame + 9, payload, payload_len);
    }

    /* Calculate CRC-32C over sync + cmd + len + payload */
    uint16_t crc_cover = 9 + payload_len;
    crc = crc32c_calculate(frame, crc_cover);

    /* Append CRC (big-endian) */
    frame[9 + payload_len + 0] = (crc >> 24) & 0xFF;
    frame[9 + payload_len + 1] = (crc >> 16) & 0xFF;
    frame[9 + payload_len + 2] = (crc >> 8) & 0xFF;
    frame[9 + payload_len + 3] = crc & 0xFF;

    frame_len = 13 + payload_len;

    /* Pad to 32-bit boundary if needed */
    uint16_t padded_len = (frame_len + 3) & ~0x3;
    if (padded_len > frame_len) {
        memset(frame + frame_len, 0, padded_len - frame_len);
    }

    /* Transmit */
    return ft601_tx_packet(frame, padded_len);
}

/*============================================================================
 * CAPTURE DATA TRANSMIT
 *============================================================================*/

int ft601_tx_capture_data(const uint8_t *record, uint16_t record_len) {
    uint8_t frame[FT601_MAX_PAYLOAD + 13];
    uint16_t payload_len;
    uint32_t crc;

    /* The record already contains timestamp, direction, type, length,
     * requester ID, tag, TC, and raw TLP bytes. We send it as-is
     * as the payload of a CMD_CAPTURE_DATA frame. */

    if (record_len > FT601_MAX_PAYLOAD) {
        return -1;
    }

    payload_len = record_len;

    /* Build frame */
    frame[0] = SYNC_MARKER_0;
    frame[1] = SYNC_MARKER_1;
    frame[2] = SYNC_MARKER_2;
    frame[3] = SYNC_MARKER_3;
    frame[4] = SYNC_MARKER_4;
    frame[5] = SYNC_MARKER_5;
    frame[6] = CMD_CAPTURE_DATA;
    frame[7] = (payload_len >> 8) & 0xFF;
    frame[8] = payload_len & 0xFF;

    memcpy(frame + 9, record, record_len);

    /* CRC-32C */
    crc = crc32c_calculate(frame, 9 + payload_len);
    frame[9 + payload_len + 0] = (crc >> 24) & 0xFF;
    frame[9 + payload_len + 1] = (crc >> 16) & 0xFF;
    frame[9 + payload_len + 2] = (crc >> 8) & 0xFF;
    frame[9 + payload_len + 3] = crc & 0xFF;

    uint16_t frame_len = 13 + payload_len;
    uint16_t padded_len = (frame_len + 3) & ~0x3;

    if (padded_len > frame_len) {
        memset(frame + frame_len, 0, padded_len - frame_len);
    }

    return ft601_tx_packet(frame, padded_len);
}

/*============================================================================
 * BYTE COUNTERS
 *============================================================================*/

uint32_t ft601_get_tx_bytes(void) {
    return g_tx_byte_count;
}

uint32_t ft601_get_rx_bytes(void) {
    return g_rx_byte_count;
}
